update init.d script

diff --git a/rulisp b/rulisp
--- a/rulisp
+++ b/rulisp
@@ -14,30 +14,37 @@ start () {
 
     export LC_ALL="ru_RU.UTF-8"
 
-    sbcl --dynamic-space-size 400 --noinform --no-userinit --no-sysinit --load /usr/share/rulisp/rulisp-daemon.lisp start
+    sbcl --dynamic-space-size 400 --noinform --no-userinit --no-sysinit --load /etc/restas-daemon.lisp /etc/rulisp.daemon start
 		       
 	[ $? -eq 0 ] && echo "done." || echo "failed!"
 }
 
 nodaemon () {
-    sbcl --dynamic-space-size 400 --noinform --no-userinit --no-sysinit --load /usr/share/rulisp/rulisp-daemon.lisp nodaemon
+    sbcl --dynamic-space-size 400 --noinform --no-userinit --no-sysinit --load /etc/restas-daemon.lisp /etc/rulisp.daemon nodaemon
 }
 
 stop () {
 	echo -n "Stopping rulisp server... "
-    sbcl --noinform --no-userinit --no-sysinit --load /usr/share/rulisp/rulisp-daemon.lisp kill
+    sbcl --noinform --no-userinit --no-sysinit --load /etc/restas-daemon.lisp /etc/rulisp.daemon kill
+    
+	[ $? -eq 0 ] && echo "done." || echo "failed!"
+}
+
+restart () {
+	echo -n "Restart rulisp server... "
+    sbcl --noinform --no-userinit --no-sysinit --load /etc/restas-daemon.lisp /etc/rulisp.daemon restart
     
 	[ $? -eq 0 ] && echo "done." || echo "failed!"
 }
 
 help () {
-	echo "Usage: $0 <start|stop|restart>"
+	echo "Usage: $0 <start|stop|restart|nodaemon>"
 }
 
 case "$1" in
     start) start ;;
     stop) stop ;;
     nodaemon) nodaemon ;;
-    restart) stop && start ;;
+    restart) restart ;;
     *) help ;;
 esac
